import type { FormTemplate } from './types';

export const formTemplates: FormTemplate[] = [
  {
    id: 'job-application',
    title: 'Job Application Form',
    description: 'Complete a standard online job application with guidance on each field',
    fields: [
      {
        id: 'fullName',
        label: 'Full Name',
        type: 'text',
        required: true,
        tip: 'Use your legal name as it appears on official documents',
        example: 'John Michael Smith',
      },
      {
        id: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        tip: 'Use a professional email address. Avoid nicknames or unprofessional handles.',
        example: 'john.smith@email.com',
      },
      {
        id: 'phone',
        label: 'Phone Number',
        type: 'tel',
        required: true,
        tip: 'Include your country code if applying internationally. Ensure this number is active.',
        example: '+1 (555) 123-4567',
      },
      {
        id: 'experience',
        label: 'Relevant Experience',
        type: 'textarea',
        required: true,
        tip: 'Highlight specific skills and achievements relevant to the job. Use bullet points for clarity.',
        example: '• 3 years customer service experience\n• Proficient in CRM software\n• Resolved 95% of customer issues on first contact',
      },
      {
        id: 'availability',
        label: 'Availability',
        type: 'select',
        required: true,
        tip: 'Be honest about when you can start. Employers appreciate transparency.',
        example: 'Immediately',
        options: ['Immediately', 'Within 2 weeks', 'Within 1 month', 'More than 1 month'],
      },
    ],
  },
  {
    id: 'survey',
    title: 'Online Survey Form',
    description: 'Complete survey forms for market research or feedback opportunities',
    fields: [
      {
        id: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        tip: 'Your first name as you prefer to be addressed',
        example: 'Sarah',
      },
      {
        id: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        tip: 'Use an email you check regularly for survey invitations',
        example: 'sarah.jones@email.com',
      },
      {
        id: 'age',
        label: 'Age Range',
        type: 'select',
        required: true,
        tip: 'Select your age range. This helps with demographic analysis.',
        example: '25-34',
        options: ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
      },
      {
        id: 'interests',
        label: 'Areas of Interest',
        type: 'textarea',
        required: false,
        tip: 'List topics you are interested in. This helps match you with relevant surveys.',
        example: 'Technology, Health & Wellness, Travel, Personal Finance',
      },
    ],
  },
  {
    id: 'registration',
    title: 'Platform Registration',
    description: 'Register for freelance platforms, job boards, or online services',
    fields: [
      {
        id: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        tip: 'Choose a professional username. This may be visible to potential clients or employers.',
        example: 'john_smith_pro',
      },
      {
        id: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        tip: 'Use an email you check daily. This will be your primary contact method.',
        example: 'john.smith@email.com',
      },
      {
        id: 'skills',
        label: 'Skills & Expertise',
        type: 'textarea',
        required: true,
        tip: 'List your key skills. Be specific and honest about your capabilities.',
        example: 'Content Writing, SEO, Social Media Management, WordPress, Adobe Creative Suite',
      },
      {
        id: 'bio',
        label: 'Professional Bio',
        type: 'textarea',
        required: true,
        tip: 'Write a brief professional summary. Focus on your strengths and what makes you unique.',
        example: 'Experienced content writer with 5+ years creating engaging blog posts and web copy. Specialized in tech and business topics.',
      },
    ],
  },
];
